//
//  SKEvent.h
//  SK Codebase
//
//  Created by Martin Videfors on 2012-02-01.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "SKEntity.h"

@interface SKEvent : SKEntity {
    NSInteger ActionId;
    NSString *AutoGenerated;
    NSString *ControlledByRule;
    NSString *EventDate;
    NSString *DebugInfo;
    NSInteger DeviceId;
    NSString *DeviceName;
    NSString *DeviceNativeId;
    NSInteger DimLevel;
    NSString *Forced;
    NSString *Source;
    NSString *ScenarioName;
    NSString *EntityType;
    NSInteger ScenarioId;
}

@property (atomic, assign) NSInteger ActionId;
@property (atomic, assign) NSInteger DeviceId;
@property (atomic, assign) NSInteger DimLevel;
@property (atomic, retain) NSString *AutoGenerated;
@property (atomic, retain) NSString *ControlledByRule;
@property (atomic, retain) NSString *EventDate;
@property (atomic, retain) NSString *DebugInfo;
@property (atomic, retain) NSString *DeviceName;
@property (atomic, retain) NSString *DeviceNativeId;
@property (atomic, retain) NSString *Forced;
@property (atomic, retain) NSString *Source;
@property (atomic, retain) NSString *EntityType;
@property (atomic, assign) NSInteger ScenarioId;
@property (atomic, retain) NSString *ScenarioName;

@end