//
//  SKEvent.m
//  SK Codebase
//
//  Created by Martin Videfors on 2012-02-01.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import "SKEvent.h"

@implementation SKEvent

//------------------------------------------------------------
// Target properties
@synthesize EntityType;
@synthesize DeviceId;
@synthesize DeviceName;
@synthesize DeviceNativeId;
@synthesize ScenarioId;
@synthesize ScenarioName;

//------------------------------------------------------------
// Action properties
@synthesize ActionId;
@synthesize DimLevel;
@synthesize EventDate;

//------------------------------------------------------------
// Behavior properties
@synthesize AutoGenerated;
@synthesize ControlledByRule;
@synthesize DebugInfo;
@synthesize Forced;

//------------------------------------------------------------
// Misc properties
@synthesize Source;

@end
