//
//  SKEvent.h
//  SK Codebase
//
//  Created by Martin Videfors on 2012-02-01.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "SKEntity.h"

@interface SKEvent : SKEntity

//------------------------------------------------------------
// Target properties
@property (nonatomic, copy) NSString *EntityType;
@property (nonatomic, assign) NSInteger DeviceId;
@property (nonatomic, copy) NSString *DeviceName;
@property (nonatomic, copy) NSString *DeviceNativeId;
@property (nonatomic, assign) NSInteger ScenarioId;
@property (nonatomic, copy) NSString *ScenarioName;

//------------------------------------------------------------
// Action properties
@property (nonatomic, assign) NSInteger ActionId;
@property (nonatomic, assign) NSInteger DimLevel;
@property (nonatomic, copy) NSString *EventDate;

//------------------------------------------------------------
// Behavior properties
@property (nonatomic, copy) NSString *AutoGenerated;
@property (nonatomic, copy) NSString *ControlledByRule;
@property (nonatomic, copy) NSString *DebugInfo;
@property (nonatomic, copy) NSString *Forced;

//------------------------------------------------------------
// Misc properties
@property (nonatomic, copy) NSString *Source;

@end