//
//  SKEvent.m
//  SK Codebase
//
//  Created by Martin Videfors on 2012-02-01.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import "SKEvent.h"

@implementation SKEvent

@synthesize ActionId;
@synthesize AutoGenerated;
@synthesize ControlledByRule;
@synthesize DeviceId;
@synthesize DimLevel;
@synthesize DebugInfo;
@synthesize DeviceName;
@synthesize DeviceNativeId;
@synthesize EventDate;
@synthesize Forced;
@synthesize Source;
@synthesize ScenarioId;
@synthesize ScenarioName;
@synthesize EntityType;

@end
